name: data_layer_hive
description: Hive implementation of DataLayer.
version: 0.0.1-beta.1
repository: https://github.com/craiglabenz/dash_data_layer

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  data_layer: ^0.0.1-beta.4
  equatable: ^2.0.7
  hive_ce: ^2.15.1
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.6
  very_good_analysis: ^10.0.0
