name: data_layer
description: Isolated data layer abstractions for Dart and Flutter apps
version: 0.0.1-beta.1
repository: https://github.com/craiglabenz/dash_data_layer
environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  crypt: ^4.3.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  logging: ^1.3.0
  matcher: ^0.12.17
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
  very_good_analysis: ^10.0.0
