name: data_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.10.0-290.1.beta

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
  very_good_analysis: ^10.0.0
